![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)


1.21.1


#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [3]:
# your code here

a = np.random.random(size=(3, 2, 5))


#### 4. Print *a*.


In [4]:
# your code here

a


array([[[0.70205377, 0.31016122, 0.39643964, 0.83634589, 0.92655459],
        [0.32531188, 0.94617351, 0.58322426, 0.14963805, 0.03107289]],

       [[0.6616122 , 0.11064399, 0.55574171, 0.31906814, 0.54902422],
        [0.08608132, 0.14037234, 0.46324749, 0.73525699, 0.99804218]],

       [[0.49415283, 0.40050032, 0.125325  , 0.81780538, 0.66388284],
        [0.51543846, 0.21472074, 0.5570828 , 0.93581118, 0.00942273]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [5]:
# your code here - Option 1

b = np.ones(shape = (5, 2, 3), dtype = int)


In [6]:
# your code here - Option 2

b_option2 = np.full((5, 2, 3), 1)
b_option2


array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [7]:
# your code here

b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
# your code here

np.size(a) == np.size(b)


True

In [13]:
a.size == b.size

True

In [16]:
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
# your answer here

a + b

# With a ( + ) sign: NO, they don't have the same shape,
# a shape is (3,2,5) and b has shape (5,2,3)


ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

In [20]:
np.concatenate([a, b], axis = 0)

# With 'concatenate' at axis = 0 (rows)

# Also not possible to add a and b
# "ValueError: all the input array dimensions # for the concatenation
# axis must match exactly, but along dimension 2, the array at index 0
# has size 5 and the array at index 1 has size 3


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 5 and the array at index 1 has size 3

In [21]:
np.concatenate([a, b], axis = 1)

# With 'concatenate' at axis = 1 (columns)

# Axis 1, also NO, due to "ValueError: all the input array dimensions
# for the concatenation axis must match exactly, but along dimension 0,
# the array at index 0 has size 3 and the array at index 1 has size 5


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 5

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.
*Hint: The tranpose of 5x2x3 is 3x2x5*

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [24]:
# your code here

c = b.transpose()
c


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [26]:
# can also be T only

c = b.T
c


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [28]:
# your code/answer here

# It works since both have same shape (3,2,5)

d = a + c
d


array([[[1.70205377, 1.31016122, 1.39643964, 1.83634589, 1.92655459],
        [1.32531188, 1.94617351, 1.58322426, 1.14963805, 1.03107289]],

       [[1.6616122 , 1.11064399, 1.55574171, 1.31906814, 1.54902422],
        [1.08608132, 1.14037234, 1.46324749, 1.73525699, 1.99804218]],

       [[1.49415283, 1.40050032, 1.125325  , 1.81780538, 1.66388284],
        [1.51543846, 1.21472074, 1.5570828 , 1.93581118, 1.00942273]]])

In [29]:
d.shape

(3, 2, 5)

In [30]:
# Option 2

d = np.add(a, c)
d


array([[[1.70205377, 1.31016122, 1.39643964, 1.83634589, 1.92655459],
        [1.32531188, 1.94617351, 1.58322426, 1.14963805, 1.03107289]],

       [[1.6616122 , 1.11064399, 1.55574171, 1.31906814, 1.54902422],
        [1.08608132, 1.14037234, 1.46324749, 1.73525699, 1.99804218]],

       [[1.49415283, 1.40050032, 1.125325  , 1.81780538, 1.66388284],
        [1.51543846, 1.21472074, 1.5570828 , 1.93581118, 1.00942273]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
# your code/answer here

print(a)


[[[0.70205377 0.31016122 0.39643964 0.83634589 0.92655459]
  [0.32531188 0.94617351 0.58322426 0.14963805 0.03107289]]

 [[0.6616122  0.11064399 0.55574171 0.31906814 0.54902422]
  [0.08608132 0.14037234 0.46324749 0.73525699 0.99804218]]

 [[0.49415283 0.40050032 0.125325   0.81780538 0.66388284]
  [0.51543846 0.21472074 0.5570828  0.93581118 0.00942273]]]


In [32]:
print(d)


[[[1.70205377 1.31016122 1.39643964 1.83634589 1.92655459]
  [1.32531188 1.94617351 1.58322426 1.14963805 1.03107289]]

 [[1.6616122  1.11064399 1.55574171 1.31906814 1.54902422]
  [1.08608132 1.14037234 1.46324749 1.73525699 1.99804218]]

 [[1.49415283 1.40050032 1.125325   1.81780538 1.66388284]
  [1.51543846 1.21472074 1.5570828  1.93581118 1.00942273]]]


In [34]:
print('')
print(f"\033[1;43m Each element in d has now it's own value plus the value at same index in a ")
print('')



 Each element in d has now it's own value plus the value at same index in a 



#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
# your code here

e = a * c
e


array([[[0.70205377, 0.31016122, 0.39643964, 0.83634589, 0.92655459],
        [0.32531188, 0.94617351, 0.58322426, 0.14963805, 0.03107289]],

       [[0.6616122 , 0.11064399, 0.55574171, 0.31906814, 0.54902422],
        [0.08608132, 0.14037234, 0.46324749, 0.73525699, 0.99804218]],

       [[0.49415283, 0.40050032, 0.125325  , 0.81780538, 0.66388284],
        [0.51543846, 0.21472074, 0.5570828 , 0.93581118, 0.00942273]]])

In [37]:
# Option 2

e = np.multiply(a, c)
e


array([[[0.70205377, 0.31016122, 0.39643964, 0.83634589, 0.92655459],
        [0.32531188, 0.94617351, 0.58322426, 0.14963805, 0.03107289]],

       [[0.6616122 , 0.11064399, 0.55574171, 0.31906814, 0.54902422],
        [0.08608132, 0.14037234, 0.46324749, 0.73525699, 0.99804218]],

       [[0.49415283, 0.40050032, 0.125325  , 0.81780538, 0.66388284],
        [0.51543846, 0.21472074, 0.5570828 , 0.93581118, 0.00942273]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [38]:
# your code/answer here

np.size(e) == np.size(a)


True

In [42]:
print(a.shape)
print(e.shape)


(3, 2, 5)
(3, 2, 5)


In [41]:
e == a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [40]:
# YES, since both have same values and shape


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
# your code here

d_max = np.max(d)
d_max

1.9980421810892106

In [45]:
# Option 2

d_max = d.max()
print(d_max)

1.9980421810892106


In [ ]:
d_min = np.min(d)
d_min

In [48]:
# Option 2

d_min = d.min()
print(d_min)

1.0094227339157684


In [46]:
d_mean = np.mean(d)
d_mean

1.4853402857124156

In [47]:
# Option 2

d_mean = d.mean()
print(d_mean)

1.4853402857124156


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 3x2x5) as *d* using `np.empty`.


In [49]:
# your code here

f = np.empty([3, 2, 5])
f


array([[[0.70205377, 0.31016122, 0.39643964, 0.83634589, 0.92655459],
        [0.32531188, 0.94617351, 0.58322426, 0.14963805, 0.03107289]],

       [[0.6616122 , 0.11064399, 0.55574171, 0.31906814, 0.54902422],
        [0.08608132, 0.14037234, 0.46324749, 0.73525699, 0.99804218]],

       [[0.49415283, 0.40050032, 0.125325  , 0.81780538, 0.66388284],
        [0.51543846, 0.21472074, 0.5570828 , 0.93581118, 0.00942273]]])